from .agents import STORE_AGENT_PROMPT
from .tasks import MESSAGE_CATEGORIZER_TASK
from .subgraphs import ORDERS_AGENT_PROMPT, PRODUCTS_AGENT_PROMPT

MESSAGE_CATEGORIZER_PROMPT = f"{STORE_AGENT_PROMPT}\n{MESSAGE_CATEGORIZER_TASK}"