from .agents import STORE_AGENT_PROMPT, SUPPORT_CLERK_PROMPT
from .tasks import MESSAGE_CATEGORIZER_TASK, SUPPORT_AGENT_TASK

MESSAGE_CATEGORIZER_PROMPT = f"{STORE_AGENT_PROMPT}\n{MESSAGE_CATEGORIZER_TASK}"

SUPPORT_AGENT_TASK = f"{SUPPORT_CLERK_PROMPT}\n{SUPPORT_AGENT_TASK}"